services:
  # service name
  apache:
    # path to Dockerfile
    build: .
    # list of portforwards
    ports:
      - "80:80"
    # tell sass to listen to changes (automatically compile)
    command: sass --no-cache --sourcemap=none --watch /workspaces/lamp-devcontainer/scss:/var/www/html/css
